version: "3.8"

services:
    docker-bench-security:
        build:
            context: .
            dockerfile: docker-bench-security.dockerfile

        cap_add:
            - audit_control
        labels:
            - docker_bench_security
        network_mode: host
        pid: host
        stdin_open: true
        tty: true
        volumes:
            - /var/lib:/var/lib:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /usr/lib/systemd:/usr/lib/systemd:ro
            - /etc:/etc:ro
